[package]
name = "orga"
version = "0.1.10"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "State machine engine"
license = "MIT"

[dependencies]
failure = "0.1.8"
abci2 = { git = "https://github.com/nomic-io/abci2", optional = true }
merk = { git = "https://github.com/nomic-io/merk", rev = "42a2943852b23b61ec9159a7de6c63003f213796", optional = true }
tendermint-rpc = { version = "0.21.0", features = ["http-client"], optional = true }
tendermint = { version = "0.21.0", optional = true }
tendermint-proto = { version = "0.21.0", optional = true }
orga-macros = { path = "macros", version = "0.2.1" }
seq-macro = "0.1.4"
log = "0.4.8"
hex-literal = "0.3.3"
sha2 = "0.9.5"
is_executable = "1.0.1"
reqwest = {version = "0.11.4", features = ["blocking"]}
flate2 = "1.0.20"
tar = "0.4.33"
ed = { git = "https://github.com/nomic-io/ed.git", rev = "8689899b1518ca51a989fe250eff101968fa7828"}
toml_edit = "0.2.0"
datetime = "0.5.2"
prost = {version = "0.7", optional = true}
home = "0.5.3"
rand_core = { version = "0.5", optional = true}
ed25519-dalek = {version = "1", optional = true}
bech32 = "0.8.1"
async-trait = "0.1.51"
futures-lite = "1.12.0"

[dev-dependencies]
tempdir = "0.3.7"
tokio = { version = "1.11.0", features = ["rt", "macros"] }

[package.metadata.docs.rs]
features = ["abci", "merk"]

[features]
abci = ["abci2", "tendermint", "tendermint-rpc", "tendermint-proto", "prost", "rand_core", "ed25519-dalek"]

[profile.release]
lto = true

[[example]]
name = "counter"
required-features = ["merk", "abci"]

[[example]]
name = "simple-coin"
required-features = ["merk", "abci"]
