[package]
name = "orga"
version = "0.1.10"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
description = "State machine engine"
license = "MIT"

[dependencies]
failure = "0.1.8"
abci2 = { git = "https://github.com/nomic-io/abci2", optional = true }
merk = { git = "https://github.com/nomic-io/merk", branch = "develop", optional = true }
tendermint-rpc = { version = "0.21.0", features = ["http-client"], optional = true }
tendermint = { version = "0.21.0", optional = true }
tendermint-proto = { version = "0.21.0", optional = true }
orga-macros = { path = "macros", version = "0.1.0" }
seq-macro = "0.1.4"
log = "0.4.8"
blocking = "0.4.7"
ed = "0.2.0"

[dev-dependencies]
tempdir = "0.3.7"

[package.metadata.docs.rs]
features = ["abci", "merk"]

[features]
abci = ["abci2", "tendermint", "tendermint-rpc", "tendermint-proto"]

[profile.release]
lto = true

[[example]]
name = "counter"
required-features = ["merk", "abci"]

[[example]]
name = "counter_replicant"
required-features = ["merk", "abci"]
